services:
  smart-pocket-dev-web:
    build:
      context: ./
      dockerfile: ./infrastructure/docker/Web.dev.dockerfile
    container_name: smart-pocket-dev-web
    volumes:
      - ./apps/smart-pocket-backend/src:/app/backend/src:delegated
      - ./apps/smart-pocket-backend/package.json:/app/backend/package.json:delegated
      - ./apps/smart-pocket-web/src:/app/frontend/src:delegated
      - ./apps/smart-pocket-web/package.json:/app/frontend/package.json:delegated
      - /app/backend/node_modules
      - /app/frontend/node_modules
      - ./keys:/data/keys:ro
    environment:
      - NODE_ENV=development
      - API_KEYS=${API_KEYS}
      - ACTUAL_BUDGET_SERVER_URL=${ACTUAL_BUDGET_SERVER_URL}
      - ACTUAL_BUDGET_PASSWORD=${ACTUAL_BUDGET_PASSWORD}
      - ACTUAL_BUDGET_ID=${ACTUAL_BUDGET_ID}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID:-}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME:-}
    restart: unless-stopped
    ports:
      - "3000:80"

  smart-pocket-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: smart-pocket-cloudflared
    command: 
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN}