/**
 * Standard error codes for the application
 * Used with ApplicationError for structured error responses
 */
const ErrorCodes = {
  // Authentication errors (4xx)
  INVALID_API_KEY: 'INVALID_API_KEY',
  MISSING_AUTH_HEADER: 'MISSING_AUTH_HEADER',
  INVALID_AUTH_HEADER: 'INVALID_AUTH_HEADER',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  EXPIRED_ACCESS_TOKEN: 'EXPIRED_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  EXPIRED_REFRESH_TOKEN: 'EXPIRED_REFRESH_TOKEN',

  // Validation errors (4xx)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Resource errors (4xx)
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Server errors (5xx)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export default ErrorCodes;
export { ErrorCodes };
