services:
  smart-pocket-prod-backend:
    image: ghcr.io/patterueldev/smart-pocket/backend:latest
    container_name: smart-pocket-prod-backend
    volumes:
      - ./keys:/data/keys:ro
    environment:
      - NODE_ENV=production
      - API_KEYS=${API_KEYS}
      - ACTUAL_BUDGET_SERVER_URL=${ACTUAL_BUDGET_SERVER_URL}
      - ACTUAL_BUDGET_PASSWORD=${ACTUAL_BUDGET_PASSWORD}
      - ACTUAL_BUDGET_ID=${ACTUAL_BUDGET_ID}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID:-}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME:-}
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: 
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN}