version: 1.0
provider:
  name: openfaas
  gateway: https://functions.patteruel.dev
functions:
  dev-sp-sheets-sync:
    lang: node22
    handler: ./sheets-sync
    image: git.patteruel.dev/pat/smart-pocket/sheets-sync:dev

  dev-sp-transactions:
    lang: node22
    handler: ./transactions
    image: git.patteruel.dev/pat/smart-pocket/transactions:dev
