version: 1.0
provider:
  name: openfaas
  gateway: https://functions.patteruel.dev
functions:
  dev-sp-sheets-sync:
    lang: node22
    handler: ./sheets-sync
    image: git.patteruel.dev/pat/smart-pocket/sheets-sync:dev
    environment:
      ACTUAL_BUDGET_SERVER_URL: some-server-url
      ACTUAL_BUDGET_PASSWORD: some-password
      ACTUAL_BUDGET_ID: some-budget-id
      ACTUAL_BUDGET_CURRENCY: PHP
    secrets:
      - actual-budget-password


  dev-sp-transactions:
    lang: node22
    handler: ./transactions
    image: git.patteruel.dev/pat/smart-pocket/transactions:dev
