name: Basic Checks

on:
  push:
    branches:
      - main

jobs:
  basic-checks:
    steps:
      - name: Basic Check - Checking if Gitea Runner is working
        run: echo "Gitea Runner is working"